apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-site-svc
spec:
  selector:
    app: nginx-site
  ports:
  - port: 80
    targetPort: 80
